rnapp:
  extends:
    file: docker-compose.yml
    service: rnapp
      volumes: /Users/joshua/projects/rnapp:/app
      ports:
        - "80:80"
packager:
  extends:
    file: docker-compose.yml
    service: packager044
      volumes:
        - /Users/joshua/projects/rnapp/app_js:/js
