rnapp:
  build: .
  restart: always
  env_file: .env.production
  volumes:
    - /home/app/rails/rnapp:/app
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: production
    VIRTUAL_HOST: rnapp.org,www.rnapp.org

postgres:
  restart: always
  env_file: .env.production
  image: postgres

rnappstaging:
  restart: always
  build: .
  env_file: .env.production
  volumes:
    - /home/app/rails/rnapp_staging:/app
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: staging
    VIRTUAL_HOST: staging.rnapp.org

postgres:
  restart: always
  env_file: .env.production
  image: postgres

packager042:
  restart: always
  image: "packager:0.4.2"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager042.rnapp.org
  volumes:
    - /home/app/rails/rnapp/app_js:/js

packager043:
  restart: always
  image: "packager:0.4.3"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager043.rnapp.org
  volumes:
    - /home/app/rails/rnapp/app_js:/js

packager044:
  restart: always
  image: "packager:0.4.4"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager044.rnapp.org
  volumes:
    - /home/app/rails/rnapp/app_js:/js

packager050rc1:
  restart: always
  image: "packager:0.5.0-rc1"
  env_file: .env.production
  environment:
    VIRTUAL_HOST: packager050rc1.rnapp.org
  volumes:
    - /home/app/rails/rnapp/app_js:/js

proxy:
  restart: always
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  environment:
    DEFAULT_HOST: rnapp.org
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /home/app/certs:/etc/nginx/certs

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

worker:
  restart: always
  build: .
  command: bundle exec sidekiq -e production -c 25
  volumes:
    - /home/app/rails/rnapp:/app
  env_file: .env.production
  links:
    - postgres
    - redis
    - cache

logger:
  image: progrium/logspout
  command: syslog://logs.papertrailapp.com:13269
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
